SET search_path = "RakeMyMovie";

SELECT * FROM Movies
	WHERE movie_title = '$movie_title';

--b
SELECT A.*, MA.ROLE
	FROM ACTOR A, MOVACT MA, MOVIES M
	WHERE M.MOVIE_TITLE = '$title' AND M.MOVIE_ID = MA.MOVIE_ID AND MA.ACTOR_ID = A.ACTOR_ID;

--c

SELECT DISTINCT D.DIR_NAME, S.STUDIO_NAME, M.MOVIE_RELEASE_DATE
	FROM DIRECTOR D, STUDIO S, MOVIES M, GENRE G, MOVGEN MG, MOVDIR MD, SPONSOR SP
	WHERE G.GENRE_NAME = 'Action' AND
		G.GENRE_ID = MG.GENRE_ID AND
		MG.MOVIE_ID = M.MOVIE_ID AND
		MG.MOVIE_ID = MD.DIR_ID AND
		MD.DIR_ID = D.DIR_ID AND
		MG.MOVIE_ID = SP.MOVIE_ID AND
		SP.STUDIO_ID = S.STUDIO_ID;

--d
SELECT A.*, D.*, S.*
FROM ACTOR A, DIRECTOR D, STUDIO S, MOVACT MA, MOVDIR MD, SPONSOR SP
WHERE A.ACTOR_ID = (SELECT A.ACTOR_ID
			FROM ACTOR A, MOVACT MA
			WHERE A.ACTOR_ID = MA.ACTOR_ID
			GROUP BY A.ACTOR_ID
			ORDER BY COUNT(A.ACTOR_ID) DESC
			LIMIT 1) AND
 	MA.ACTOR_ID = A.ACTOR_ID AND 
	MA.MOVIE_ID = MD.MOVIE_ID AND
	MD.DIR_ID = D.DIR_ID AND
	MA.MOVIE_ID = SP.MOVIE_ID AND
	SP.STUDIO_ID = S.STUDIO_ID;

--e
SELECT * FROM REVIEW
FROM ACTOR A1, ACTOR A2, Movie M, 
WHERE


--f
SELECT M.MOVIE_TITLE, AVG(R.REVIEW_RATING)
FROM REVIEW R, MOVREV MR, MOVIES M
WHERE R.REVIEW_ID = MR.REVIEW_ID AND
MR.MOVIE_ID = M.MOVIE_ID
GROUP BY M.MOVIE_TITLE
ORDER BY AVG(R.REVIEW_RATING) DESC
LIMIT 10;

--g
SELECT M.MOVIE_TITLE, G.GENRE_NAME, AVG(R.REVIEW_RATING)
FROM MOVIES M, GENRE G, REVIEW R, MOVGEN MG
WHERE
	M.MOVIE_ID = (SELECT M.MOVIE_ID
		FROM REVIEW R, MOVREV MR, MOVIES M
		WHERE R.REVIEW_ID = MR.REVIEW_ID AND
		MR.MOVIE_ID = M.MOVIE_ID
		GROUP BY M.MOVIE_ID
		ORDER BY AVG(R.REVIEW_RATING) DESC
		LIMIT 1) AND --returns the ID of the top rated movie
	M.MOVIE_ID = MG.MOVIE_ID AND
	MG.GENRE_ID = G.GENRE_ID
	GROUP BY M.MOVIE_TITLE, G.GENRE_NAME


--gives movie and average rating for the movie
SELECT M.MOVIE_TITLE, AVG(R.REVIEW_RATING)
FROM REVIEW R, MOVREV MR, MOVIES M
WHERE R.REVIEW_ID = MR.REVIEW_ID AND
MR.MOVIE_ID = M.MOVIE_ID
GROUP BY M.MOVIE_TITLE
ORDER BY AVG(R.REVIEW_RATING) DESC

--count of the # of ratings a movie has
