SET search_path = "RakeMyMovie";

SELECT * FROM Movies
	WHERE movie_title = '$movie_title';

--b
SELECT A.*, MA.ROLE
	FROM ACTOR A, MOVACT MA, MOVIES M
	WHERE M.MOVIE_TITLE = '$title' AND M.MOVIE_ID = MA.MOVIE_ID AND MA.ACTOR_ID = A.ACTOR_ID;

--c

SELECT DISTINCT D.DIR_NAME, S.STUDIO_NAME, M.MOVIE_RELEASE_DATE
	FROM DIRECTOR D, STUDIO S, MOVIES M, GENRE G, MOVGEN MG, MOVDIR MD, SPONSOR SP
	WHERE G.GENRE_NAME = 'Action' AND
		G.GENRE_ID = MG.GENRE_ID AND
		MG.MOVIE_ID = M.MOVIE_ID AND
		MG.MOVIE_ID = MD.DIR_ID AND
		MD.DIR_ID = D.DIR_ID AND
		MG.MOVIE_ID = SP.MOVIE_ID AND
		SP.STUDIO_ID = S.STUDIO_ID;






SELECT A.ACTOR_NAME, D.DIR_NAME, S.STUDIO_NAME
	FROM ACTOR A, DIRECTOR D, STUDIO S, MOVACT MA, MOVDIR MD, SPONSOR SP
	

SELECT A.ACTOR_NAME, MA.ACTOR_ID, COUNT(*) AS FREQUENCY
FROM ACTOR A, MOVACT MA
GROUP BY MA.ACTOR_ID
ORDER BY COUNT(*) DESC;


SELECT ACTOR_ID, COUNT(*) AS FREQUENCY
FROM MOVACT
GROUP BY ACTOR_ID
ORDER BY COUNT(*) DESC;


SELECT MA.ACTOR_ID, COUNT(MA.ACTOR_ID) AS FREQUENCY
FROM MOVACT MA
GROUP BY MA.ACTOR_ID
ORDER BY COUNT(*) DESC;


SELECT A.ACTOR_NAME, D.DIR_NAME, S.STUDIO_NAME
	FROM ACTOR A, DIRECTOR D, STUDIO S, MOVACT MA, MOVDIR MD, SPONSOR SP
WHERE
A.ACTOR_ID = 

MA.ACTOR_ID = A.ACTOR_ID AND
MD.MOVIE_ID = MA.MOVIE_ID AND
MA.MOVIE_ID = SP.MOVIE_ID AND
SP.MOVIE_ID = S.MOVIE_ID


(SELECT MA.ACTOR_ID, COUNT(MA.ACTOR_ID) AS FREQUENCY
FROM MOVACT MA
GROUP BY MA.ACTOR_ID
ORDER BY COUNT(*) DESC;)