SET search_path = "Test";

-- CREATE TABLE RAKEUSER
-- (USER_ID SERIAL PRIMARY KEY,
-- USER_NAME VARCHAR(35) NOT NULL,
-- USER_EMAIL TEXT NOT NULL,
-- USER_PASSWORD TEXT NOT NULL, 
-- USER_GENDER CHAR(1),
-- USER_DOB DATE,
-- USER_ICON TEXT,
-- USER_ISADMIN BOOLEAN DEFAULT FALSE,
-- UNIQUE(USER_EMAIL));

-- INSERT INTO RAKEUSER (USER_NAME, USER_EMAIL, USER_PASSWORD, USER_GENDER, USER_DOB, USER_ICON)
-- VALUES
-- ('Abigael', 'abigael.tremblay@gmail.com', '1234', 'F', '22 April 1990', 'folder/folder/filename');

SELECT * FROM RAKEUSER;