INSERT INTO STUDIO (STUDIO_NAME)
VALUES
('100 Bares'),
('8:38 Productions'),
('A Band Apart'),
('A24'),
('Act III'),
('Act III Communications'),
('Adam Fields Productions'),
('AKFPL'),
('Akira Committee Company Ltd.'),
('Alcon Entertainment'),
('Alfran Productions'),
('Alfred J. Hitchcock Productions'),
('Alpha'),
('Altavista Films'),
('Amblin Entertainment'),
('AMLF'),
('Anonymous Content'),
('Appian Way'),
('Art Linson Productions'),
('Arte'),
('Artisan Entertainment'),
('Artists Entertainment Complex'),
('Arturo GonzÃ¡lez Producciones CinematogrÃ¡ficas'),
('Asghar Farhadi'),
('Ashton Productions'),
('Atlas Entertainment'),
('B.H. Finance C.V.'),
('Bad Robot'),
('Bandai'),
('Basic Pictures'),
('Bavaria Film'),
('Bayerischer Rundfunk (BR)'),
('Be Gentlemen Limited Partnership'),
('Beijing ShengShi HuaRei Film Investment & Management Co.'),
('Bill/Phillips'),
('Black Bear Pictures'),
('Block 2 Pictures'),
('Blue Parrot'),
('Blumhouse Productions'),
('Bohra Bros Productions'),
('Bold Films'),
('Brandywine Productions'),
('Brentwood Productions'),
('Bristol Automotive'),
('Brooksfilms'),
('Bryna Productions'),
('Buena Vista Home Entertainment'),
('Bulletproof Cupid'),
('Buster Keaton Productions'),
('Buttercup Films Ltd.'),
('Campanile Productions'),
('Canal+'),
('Canal+'),
('Carlyle Productions'),
('Carol Reed''s Production'),
('Carolco Pictures'),
('Casbah Film'),
('Castle Rock Entertainment'),
('CatchPlay'),
('Cecchi Gori Group Tiger Cinematografica'),
('Cecchi Gori Pictures'),
('Channel Four Films'),
('Charles Chaplin Productions'),
('Chartoff-Winkler Productions'),
('Chenault Productions'),
('China Film Co-Production Corporation'),
('Cinema 86'),
('Cinematograph AB'),
('Cineriz'),
('CJ Entertainment'),
('Classico'),
('Claudie Ossard Productions'),
('Cofinergie 6'),
('Columbia Pictures'),
('Columbia Pictures Corporation'),
('Compagnie Industrielle et Commerciale CinÃ©matographique (CICC)'),
('Constantin Film Produktion'),
('Corner Producciones'),
('Cristaldifilm'),
('Cross Creek Pictures'),
('Daiei Motion Picture Company'),
('Danmarks Radio (DR)'),
('Darkwoods Productions'),
('DC Comics'),
('DC Entertainment'),
('DENTSU Music And Entertainment'),
('Det Danske Filminstitut'),
('Detour Filmproduction'),
('Dimension Films'),
('Disney Enterprises'),
('Dog Eat Dog Productions Inc.'),
('Double Nickel Entertainment'),
('DreamWorks Animation'),
('DreamWorks SKG'),
('Edward Small Productions'),
('Egg Films'),
('Egg Pictures'),
('El Deseo'),
('Element Pictures'),
('Embassy International Pictures'),
('EMI Films'),
('Esperanto Filmoj'),
('Estudios Picasso'),
('Eurimages'),
('Euro Film Funding'),
('Exclusive Media Group'),
('Fantasy Films'),
('Figment Films'),
('Filmhaus Wien Universa Filmproduktions'),
('Filmsonor'),
('Finanzia San Marco'),
('First Look Media'),
('Flower Films (II)'),
('Focus Features'),
('Forward Pass'),
('Fox 2000 Pictures'),
('Fox Film Corporation'),
('Fox Searchlight Pictures'),
('Francinex'),
('Gaumont'),
('Gerber Pictures'),
('Ghoulardi Film Company'),
('Globo Filmes'),
('Goldcrest Films International'),
('Gordon Company'),
('Greenwich Film Productions'),
('Groucho II Film Partnership'),
('Hachiko'),
('Haddock Films'),
('Hakuhodo'),
('HandMade Films'),
('Hawk Films'),
('Hell''s Kitchen Films'),
('Hemdale Film'),
('Herald Ace'),
('Heritage Films'),
('Heyday Films'),
('Hollywood Pictures'),
('Horizon Pictures'),
('Horizon Pictures (II)'),
('I Remember Productions'),
('Icon Entertainment International'),
('Igor Film'),
('Imagine Entertainment'),
('Indian Paintbrush'),
('Industrial Development Corporation of South Africa'),
('Inferno Distribution'),
('Initial Entertainment Group (IEG)'),
('Instituto Nacional de Cine y Artes Audiovisuales (INCAA)'),
('International Film Investors'),
('Into the Wild'),
('Italo/Judeo Productions'),
('Jalem Productions'),
('Jar Pictures'),
('Jerry Bruckheimer Films'),
('Jersey Films'),
('Jet Tone Production'),
('Jinks/Cohen Company'),
('Jolly Film'),
('Joseph M. Schenck Productions'),
('Juno Pix'),
('Kemp Company'),
('Kennedy Miller Productions'),
('Kennedy/Marshall Company'),
('Kinberg Genre'),
('Kinostudiya ''''Mosfilm'''''),
('Kurosawa Production Co.'),
('Ladd Company'),
('Lakeshore Entertainment'),
('Lawrence Bender Productions'),
('Legendary Pictures'),
('Les Films Ariane'),
('Les Films du Carrosse'),
('Les Films du Dauphin'),
('Liberty Films (II)'),
('Lightstorm Entertainment'),
('Linson Films'),
('Lions Gate Films'),
('Lionsgate'),
('Live Entertainment'),
('Loew''s'),
('London Film Productions'),
('Long Road Productions'),
('Lucasfilm'),
('LÃ©gende Entreprises'),
('Mad Hatter Entertainment'),
('Madhouse Entertainment'),
('Malpaso Productions'),
('Malpaso Productions'),
('Mandarin Films Distribution'),
('Marvel Enterprises'),
('Marvel Entertainment'),
('Marvel Studios'),
('Matten Productions'),
('Media Asia Films'),
('Melampo Cinematografica'),
('Melodrama Pictures'),
('Mercury Productions'),
('Metro-Goldwyn-Mayer (MGM)'),
('Michael White Productions'),
('micro_scope'),
('Mimran Schur Pictures'),
('Miramax'),
('Mirisch Company'),
('Mirisch Corporation'),
('Mitsubishi'),
('Motion Picture BETA Produktionsgesellschaft'),
('Moving Picture Company (MPC)'),
('Muhan Investment'),
('Natant'),
('National Film Development Corporation of India (NFDC)'),
('National Film Trustee Company'),
('Nero-Film AG'),
('New Line Cinema'),
('Newman-Foreman Company'),
('Newmarket Capital Group'),
('Newmarket Productions'),
('Nibariki'),
('Nippon Herald Films'),
('Nippon Television Network (NTV)'),
('No Trace Camping'),
('Norddeutscher Rundfunk (NDR)'),
('O2 Filmes'),
('Ocean Films'),
('Orion Pictures'),
('Orion-Nova Productions'),
('Pacific Western'),
('Pakula-Mulligan'),
('Pandora Cinema'),
('Paradis Films'),
('Paramount Pictures'),
('Paramount Vantage'),
('Participant Media'),
('Patron Inc.'),
('Paul Gregory Productions'),
('Penthouse'),
('Peregrine'),
('Phi Group'),
('Phoenix Pictures'),
('Pixar Animation Studios'),
('Plan B Entertainment'),
('PolyGram Filmed Entertainment'),
('productioncompany'),
('Produzioni De Sica'),
('Produzioni De Sica (PDS)'),
('Produzioni Europee Associati (PEA)'),
('PSO International'),
('Python (Monty) Pictures'),
('Quad Productions'),
('R.P. Productions'),
('Radiant Film GmbH'),
('Rafran Cinematografica'),
('Rai 3'),
('Red Granite Pictures'),
('Regency Enterprises'),
('Reliance Entertainment'),
('Right of Way Films'),
('River Road Entertainment'),
('RKO Radio Pictures'),
('Rollins-Joffe Productions'),
('Roxlom Films Inc.'),
('RÃ©alisation d''art cinÃ©matographique (RAC)'),
('S.A'),
('Samuel Goldwyn Company'),
('Savoy Pictures'),
('Scott Free Productions'),
('Scott Rudin Productions'),
('See-Saw Films'),
('Selznick International Pictures'),
('Shamley Productions'),
('Shaw Brothers'),
('Shinchosha Company'),
('Show East'),
('Sibling Productions'),
('Sidus Pictures'),
('Sikelia Productions'),
('Silver Pictures'),
('Silver Screen Partners IV'),
('SKA Films'),
('SKA Films'),
('SLM Production Group'),
('Solaris'),
('Spelling Films International'),
('Splendid Pictures'),
('Spyglass Entertainment'),
('Stage 6 Films'),
('Stanley Kramer Productions'),
('Stanley Kubrick Productions'),
('Steve Tisch Company'),
('Strong Heart/Demme Production'),
('Studio Babelsberg'),
('Studio Ghibli'),
('Summit Entertainment'),
('Super Cool ManChu'),
('Svensk Filmindustri (SF)'),
('Svenska Filminstitutet (SFI)'),
('Syalis DA'),
('Syncopy'),
('SÃ©dif Productions'),
('SÃ¼ddeutscher Rundfunk (SDR)'),
('Team Todd'),
('Ten Films'),
('Tequila Gang'),
('The'),
('The Coppola Company'),
('The Noel Gay Motion Picture Company'),
('The Princess Bride Ltd.'),
('The Saul Zaentz Company'),
('This Is That Productions'),
('Thousand Words'),
('TMS Entertainment'),
('Toho Company'),
('Tokuma Japan Communications'),
('Tokuma Shoten'),
('Tornasol Films'),
('Touchstone Pictures'),
('Troublemaker Studios'),
('Truenorth Productions'),
('TS Productions'),
('TSG Entertainment'),
('Turman-Foster Company'),
('Turman-Morrissey Company'),
('Twentieth Century Fox Film Corporation'),
('Twentieth Century-Fox Productions'),
('U-Drive Productions'),
('UK Film Council'),
('Union GÃ©nÃ©rale CinÃ©matographique (UGC)'),
('United Artists'),
('Universal International Pictures (UI)'),
('Universal Pictures'),
('Universum Film (UFA)'),
('Vanguard Films'),
('Vera Films'),
('Vera Films'),
('Vertigo Entertainment'),
('Victoires Productions'),
('VideoFilmes'),
('Village Roadshow Pictures'),
('Vinod Chopra Productions'),
('Virtual Studios'),
('Walt Disney Animation Studios'),
('Walt Disney Feature Animation'),
('Walt Disney Pictures'),
('Warner Bros.'),
('Warner Independent Pictures (WIP)'),
('Weinstein Company'),
('Westdeutscher Rundfunk (WDR)'),
('Wiedemann & Berg Filmproduktion'),
('WingNut Films'),
('Wolper Organization'),
('Working Title Films'),
('Zanuck/Brown Productions'),
('Zeta Film'),
('Zoetrope Studios');